<a href="https://colab.research.google.com/github/MrAFirm/Introduction-to-Data_Analytics_-_ML/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


a = np.array([1, 2, 3])


2


In [7]:
import time
import sys

b = range(1000)
print(sys.getsizeof(5)* len(b))

28000


In [9]:
import numpy as np

c = np.arange(1000)
print(c.size * c.itemsize)

8000


In [15]:
size = 100000

L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

start = time.time()
result = [(x+y) for x, y in zip(L1, L2)]
print("Python list took: ", (time.time() - start) * 1000)

start = time.time()
result = A1 + A2
print(result)
print ("NumPy Array took: ", (time.time() - start) * 1000)


Python list took:  5.106210708618164
[     0      2      4 ... 199994 199996 199998]
NumPy Array took:  0.9400844573974609


In [24]:
import numpy as np

a = np.array([[1.1,2,3], [4,5,6], [7,8,9]])

print(a)
print(a.ndim)
print(a.itemsize)
print(a.shape)

[[1.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
2
8
(3, 3)


In [26]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = np.float64)
print(a)
print(a.itemsize)
print(a.shape)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
8
(3, 3)


In [29]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [33]:
import numpy as np

a = np.zeros([3,1], dtype = np.uint)
print(a)

[[0]
 [0]
 [0]]


In [36]:
import numpy as jeff

a = jeff.ones([3,2], dtype = jeff.uint)
print(a)

[[1 1]
 [1 1]
 [1 1]]


In [37]:
l = range(5)
print(l)

range(0, 5)


In [38]:
import numpy as np

a = np.arange(5)
print(a)

[0 1 2 3 4]


In [62]:
from textwrap import fill
import numpy as np

a = np.array(["Welcome to "])
b = np.array(["my NumPy learning progress!"])

total = a + b
print(total)

print(np.char.add(["Wel", "Bro"], ["come", "ski!"]))
print(np.char.multiply("Jordan! ", 3))
print(np.char.center("LeBron!", 21, fillchar = "~"))
print(np.char.capitalize("lebron james"))
print(np.char.title("lebron james"))
print(np.char.upper("lebron james"))
print(np.char.upper(["lebron", "james"]))
print(np.char.lower(["LEBRON", "JAMES"]))
print(np.char.split("I love basketball."))
print(np.char.splitlines("I\nlove basketball."))
print(np.char.strip(["adam", "aria", "Jordan"], 'a'))
print(np.char.join([":", ":"], ["dmy", "ymd"]))
print(np.char.replace("Teach me basketball", "me", "you"))

['Welcome to my NumPy learning progress!']
['Welcome' 'Broski!']
Jordan! Jordan! Jordan! 
~~~~~~~LeBron!~~~~~~~
Lebron james
Lebron James
LEBRON JAMES
['LEBRON' 'JAMES']
['lebron' 'james']
['I', 'love', 'basketball.']
['I', 'love basketball.']
['dam' 'ri' 'Jordan']
['d:m:y' 'y:m:d']
Teach you basketball
