In [4]:
import cv2
import numpy as np

from google.colab import files
uploaded = files.upload()

img_name_n_path = "Ponyo.png"

img = cv2.imread(img_name_n_path, cv2.IMREAD_COLOR)

# converting to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# blur
blur = cv2.GaussianBlur(img, (3, 3), cv2.BORDER_DEFAULT)

# edge cascade
canny = cv2.Canny(img, 125, 175)

# Resized img
resized = cv2.resize(img, (500,500), interpolation = cv2.INTER_CUBIC)

print("Regular Img:\n", img)
print("Grayscale Img:\n", gray)
print("Blurred Image:\n", blur)
print("Canny Img (Edge Cascade):\n", canny)
print("Resized Img:\n", resized)

cv2.waitKey(0)

Saving Ponyo.png to Ponyo (3).png
Regular Img:
 [[[ 97  93 228]
  [ 96  92 227]
  [ 93  90 225]
  ...
  [148 152  63]
  [148 152  63]
  [148 152  63]]

 [[ 97  93 228]
  [ 95  91 226]
  [ 95  91 226]
  ...
  [148 152  63]
  [148 152  63]
  [148 152  63]]

 [[ 97  93 228]
  [ 96  92 227]
  [ 96  92 227]
  ...
  [148 152  63]
  [148 152  63]
  [148 152  63]]

 ...

 [[ 74  70 166]
  [ 71  66 166]
  [ 67  64 163]
  ...
  [ 62  79 109]
  [ 62  79 109]
  [ 63  79 109]]

 [[ 71  67 165]
  [ 67  62 162]
  [ 65  61 160]
  ...
  [ 62  79 110]
  [ 62  79 110]
  [ 62  79 110]]

 [[ 70  66 165]
  [ 67  64 163]
  [ 67  63 162]
  ...
  [ 62  79 111]
  [ 62  79 111]
  [ 62  79 111]]]
Grayscale Img:
 [[134 133 131 ... 125 125 125]
 [134 132 132 ... 125 125 125]
 [134 133 133 ... 125 125 125]
 ...
 [ 99  96  94 ...  86  86  86]
 [ 97  92  91 ...  86  86  86]
 [ 96  94  93 ...  87  87  87]]
Blurred Image:
 [[[ 96  92 227]
  [ 96  92 227]
  [ 94  91 226]
  ...
  [148 152  63]
  [148 152  63]
  [148 152  

-1