In [13]:
import cv2
import numpy as np

from google.colab import files
uploaded = files.upload()

img_name_n_path = "Shaun_pic.jpg"

# Read the image
img = cv2.imread(img_name_n_path, cv2.IMREAD_COLOR)

# converting to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# blur
blur = cv2.GaussianBlur(img, (3, 3), cv2.BORDER_DEFAULT)

# edge cascade
canny = cv2.Canny(img, 125, 175)

# Resized img
resized = cv2.resize(img, (500,500), interpolation = cv2.INTER_CUBIC)

# Haar Cascade for Facial Detection.
haar_cascade = cv2.CascadeClassifier('haar_cascade.xml')
faces_rect = haar_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=3)
print(f"Number of faces found: {len(faces_rect)}\n")

print("Regular Img:\n", img)
print("Grayscale Img:\n", gray)
print("Blurred Image:\n", blur)
print("Canny Img (Edge Cascade):\n", canny)
print("Resized Img:\n", resized)

Saving haar_cascade.xml to haar_cascade.xml
Number of faces found: 1

Regular Img:
 [[[ 51 150 130]
  [ 55 154 134]
  [ 57 154 134]
  ...
  [119 127 120]
  [110 121 113]
  [109 120 112]]

 [[ 51 150 130]
  [ 52 151 131]
  [ 53 150 130]
  ...
  [117 125 118]
  [109 120 112]
  [109 120 112]]

 [[ 54 150 133]
  [ 54 150 133]
  [ 55 151 134]
  ...
  [117 125 118]
  [110 121 113]
  [110 121 113]]

 ...

 [[108 192 188]
  [108 192 188]
  [107 192 188]
  ...
  [  0  13   1]
  [  0   9   0]
  [  0   6   0]]

 [[107 191 187]
  [107 191 187]
  [106 192 186]
  ...
  [  1  15   4]
  [  0  13   5]
  [  0  11   3]]

 [[106 190 186]
  [106 190 186]
  [106 192 186]
  ...
  [  0  14   3]
  [  0  13   5]
  [  1  14   6]]]
Grayscale Img:
 [[133 137 137 ... 124 117 116]
 [133 134 133 ... 122 116 116]
 [134 134 135 ... 122 117 117]
 ...
 [181 181 181 ...   8   5   4]
 [180 180 180 ...  10   9   7]
 [179 179 180 ...   9   9  10]]
Blurred Image:
 [[[ 52 151 131]
  [ 53 151 131]
  [ 53 151 131]
  ...
  [115 1